#ifndef __JVX_DEFINE_CONSTANTS_PROC_GROUP_LOGS_H__
#define __JVX_DEFINE_CONSTANTS_PROC_GROUP_LOGS_H__

#define JVX_BUFFERING_LOGFILE

JVX_INTERFACE IjvxReportTimingLogfile
{
	virtual jvxErrorType JVX_CALLINGCONVENTION register_instance(const std::string& descr, jvxSize& id_write) = 0;
	virtual jvxErrorType JVX_CALLINGCONVENTION memory_instance(jvxUInt32** buffer, jvxSize* entries, jvxSize id_write) = 0;

	virtual jvxErrorType JVX_CALLINGCONVENTION write_single_instance(jvxSize id_write) = 0;
};

// Logfile output
// [COMPONENT_ID] [THREAD_ID] [OPERATION] [SUCCESS] [PROC_ID] [IDX_BUF_IN] [IDX_BUF_OUT] [THREAD_ID]
#define JVX_LOG_PROC_GROUPS_NUM_ENTRIES_UINT32_LOG 8

#define JVX_LOG_PROC_GROUPS_OPERATION_TRIGGER_PIPELINE_ENTER 0x1
#define JVX_LOG_PROC_GROUPS_OPERATION_TRIGGER_PIPELINE_LEAVE 0x2
#define JVX_LOG_PROC_GROUPS_OPERATION_PROCESSING_START_ENTER 0x3
#define JVX_LOG_PROC_GROUPS_OPERATION_PROCESSING_START_LEAVE 0x4
#define JVX_LOG_PROC_GROUPS_OPERATION_PROCESSING_STOP_ENTER 0x5
#define JVX_LOG_PROC_GROUPS_OPERATION_PROCESSING_STOP_LEAVE 0x6
#define JVX_LOG_PROC_GROUPS_OPERATION_PROCESSING_ENTER 0x7
#define JVX_LOG_PROC_GROUPS_OPERATION_PROCESSING_LEAVE 0x8
#define JVX_LOG_PROC_GROUPS_OPERATION_THREAD_ENTER 0x9
#define JVX_LOG_PROC_GROUPS_OPERATION_THREAD_LEAVE 0xA
#define JVX_LOG_PROC_GROUPS_OPERATION_THREAD_COMPLETE_ENTER 0xB
#define JVX_LOG_PROC_GROUPS_OPERATION_THREAD_COMPLETE_LEAVE 0xC

// #define JVX_LOG_PROC_GROUPS_OPERATION_ 0x8

#define JVX_LOG_PROC_GROUPS_SUCCESS_OK 0x0
#define JVX_LOG_PROC_GROUPS_SUCCESS_BUFFER_LOST 0x1
#define JVX_LOG_PROC_GROUPS_SUCCESS_BUFFER_NOT_READY 0x2

#endif
