	case JVX_COMPONENT_CONNECTION:
	case JVX_COMPONENT_CONFIG_PROCESSOR:
	case JVX_COMPONENT_EXTERNAL_CALL:	
	case JVX_COMPONENT_UNKNOWN:
	case JVX_COMPONENT_FACTORY_HOST:
	case JVX_COMPONENT_HOST:
	case JVX_COMPONENT_EVENTLOOP:
	case JVX_COMPONENT_DATALOGREADER:
	case JVX_COMPONENT_THREADCONTROLLER:	
	case JVX_COMPONENT_THREADS:
	case JVX_COMPONENT_CRYPT:
	case JVX_COMPONENT_WEBSERVER:
	case JVX_COMPONENT_REMOTE_CALL:
	case JVX_COMPONENT_PACKETFILTER_RULE:
	case JVX_COMPONENT_TEXT2SPEECH:
	case JVX_COMPONENT_SYSTEM_TEXT_LOG:
	case JVX_COMPONENT_LOCAL_TEXT_LOG:
#ifndef JVX_NO_SYSTEM_EXTENSIONS
#include "codeFragments/components/Hpjvx_caseStatement_othercomponents.h"
#endif
	