	case JVX_COMPONENT_RT_AUDIO_FILE_READER:
	case JVX_COMPONENT_RT_AUDIO_FILE_WRITER:
	case JVX_COMPONENT_RESAMPLER:
	case JVX_COMPONENT_DATACONVERTER:
	case JVX_COMPONENT_AUDIO_CODEC:
	case JVX_COMPONENT_AUDIO_ENCODER:
	case JVX_COMPONENT_AUDIO_DECODER: