echo off
REM !!!!! THE FOLLOWING LINE TO BE ADAPTED ACCORDING TO BUILD SYSTEM !!!!!
set JVX_SRC_PATH=%CD%\..
REM !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

set PATH=%PATH%;%JVX_SRC_PATH%/bin/tools
REM set QT_PATH_64=C:\Qt\Qt-5.15.8
REM set QT_PATH_32=R:\Qt\Qt-5.15.7-win32
set QT_PATH_64=%JVX_SRC_PATH%\sources\jvxLibraries\third_party\web\qt\qt\5.15.2\msvc2019_64
set FLUTTER_SDK_PATH=%JVX_SRC_PATH%\sources\jvxLibraries\third_party\web\flutter\flutter-3.7.4
set MATLAB_PATH_64=C:\Program Files\MATLAB\R2020a

REM We need to install python3. It will be available at <UserFolder>/AppData/Local/Programs/Python/Python311
REM Then, pybind will be available at 
SET PYTHON64_PATH=C:\Users\binaurics\AppData\Local\Programs\Python\Python311
set PYBIND_PATH=%PYTHON64_PATH%\Lib\site-packages\pybind11\share\cmake\pybind11
set PATH=%PYTHON64_PATH%;%PATH%;%JVX_SRC_PATH%/bin/tools

set TOKEN_SDK=-DJVX_RELEASE_SDK=FALSE
set TOKEN_BTOOLS=-DJVX_COMPILE_BUILDTOOLS=FALSE

REM JVX_USE_PART_OCTAVE=FALSE -> we use Matlab on this system
REM JVX_FLUTTER_UI=FALSE -> Flutter must be off for win32
REM JVX_USE_VST=FALSE -> VST hosts are all in x64

REM -DJVX_SYSTEM_USE_DATA_FORMAT_FLOAT=TRUE ^
	
set ADDITIONAL_FEATURE_TOKENS_MIN=^
	-DJVX_USE_CCACHE=FALSE ^
	-DJVX_USE_CONSOLE_APPS=TRUE ^
	-DJVX_USE_PART_OCTAVE=TRUE ^
	-DJVX_USE_PART_MATLAB=TRUE ^
	-DJVX_USE_SIMULINK=TRUE ^
	-DJVX_SYSTEM_USE_DATA_FORMAT_FLOAT=FALSE ^
	-DJVX_USE_PCAP=TRUE ^
	-DJVX_USE_PART_WEBSERVER=TRUE ^
	-DJVX_USE_BOOST=TRUE ^
	-DJVX_USE_EIGEN=TRUE ^
	-DJVX_DEPLOY_EXAMPLES=TRUE ^
	-DJVX_USE_PART_CMINPACK=TRUE ^
	-DJVX_SPLASH_SUPPRESSED=FALSE ^
	-DJVX_MATLAB_PROPERTY_GENERATOR=TRUE ^
	-DJVX_INCLUDE_EBUR128=TRUE ^
	-DJVX_USE_VST=TRUE ^
	-DJVX_FLUTTER_UI=TRUE ^
	-DJVX_USE_PYTHON=TRUE ^
	-DJVX_USE_FFMPEG=TRUE ^
	-DJVX_USE_KISSFFT=TRUE ^
	-DJVX_LIBHOST_WITH_JSON_SHOW=TRUE ^
	-DJVX_USE_PART_WASAPI=TRUE ^
	-DJVX_USE_LIBMYSOFA=TRUE ^
	-DPYBIND_PATH=%PYBIND_PATH% ^
	-DJVX_INSTALL_QT_ON_BUILD=TRUE ^
	-DJVX_USE_ORC=TRUE ^
	-DJVX_COMPILE_GOD_HOST=TRUE 

REM -DAYF_AWE_SHARED_LIBRARY_TARGET_FOLDER="C:/DSP Concepts/AWE Designer 8.C.2.4 Pro/Bin/win32-vc142-rel" -- only win32
	
REM 	-DAYFBINRENDER_SIMPLE_INSTALLER=FALSE ^
REM 	-DFLUTTER_SDK_PATH=%FLUTTER_SDK_PATH% ^
REM 	-DJVX_USE_EAQUAL=TRUE ^
REM 	-DJVX_INSTALLER_MBC=TRUE ^
REM 	-DSMTG_CREATE_PLUGIN_LINK=FALSE

set ADDITIONAL_FEATURE_TOKENS_FULL=^
	-DLIBMYSOFA_BUILD_TESTS=FALSE ^
	-DAYFBINRENDER_FFMPEG_FILE_IO=TRUE ^
	-DAYFBINRENDER_HEADTRACKER_RS232=TRUE ^
	-DAYFBINRENDER_HEADTRACKER_ART=TRUE ^
	-DJVX_INSTALLER_MBC=TRUE ^
	-DFLUTTER_SDK_PATH=%FLUTTER_SDK_PATH% ^
	-DJVX_USE_EAQUAL=TRUE ^
	-DSMTG_CREATE_PLUGIN_LINK=FALSE ^
	-DLIBMYSOFA_BUILD_TESTS=FALSE ^
	-DAYFBINRENDER_HEADTRACKER_ART=TRUE	^
	-DJVX_USE_AWE=TRUE ^
	-DJVX_USE_HDF5=TRUE ^
	-DAYF_AWE_SHARED_LIBRARY_TARGET_FOLDER="C:/DSP Concepts/AWE Designer 8.C.2.4 Pro/Bin/win32-vc142-rel" ^
	-DAYFSTARTER_SIMPLE_INSTALLER=FALSE
		
	
REM ####################### Compile options for BT builds
set JVX_GENERATOR_TOKEN_BT="Ninja"
set JVX_GENERATOR_ARCHITECTURE_BT=

REM ####################### Compile options for RT build
REM set JVX_GENERATOR_TOKEN_RT="Ninja"
REM set JVX_GENERATOR_ARCHITECTURE_RT=
REM set JVX_GENERATOR_TOKEN_RT="Visual Studio 16 2019"
REM set JVX_GENERATOR_ARCHITECTURE_RT=-A x64
set JVX_GENERATOR_TOKEN_RT="Visual Studio 17 2022"
set JVX_GENERATOR_ARCHITECTURE_RT=-A x64

REM ####################### Compile options for SDK build
set JVX_GENERATOR_TOKEN_SDK="Ninja"
set JVX_GENERATOR_ARCHITECTURE_SDK=

REM set JVX_GENERATOR_TOKEN="Ninja"
REM set JVX_GENERATOR_ARCHITECTURE=
REM set JVX_GENERATOR_TOKEN="NMake Makefiles"
REM set JVX_GENERATOR_ARCHITECTURE=
set JVX_GENERATOR_BUILDTYPE=
set JVX_RELEASE_TYPE=Debug
REM set JVX_GENERATOR_TOKEN="Ninja"
REM JVX_GENERATOR_TOKEN="\"Unix Makefiles\""

IF "%~1"=="rt" GOTO cmake_rt
IF "%~1"=="sdk" GOTO cmake_sdk
IF "%~1"=="sdk-bt" GOTO cmake_sdk_bt
IF "%~1"=="rt-bt" GOTO cmake_rt_bt
IF "%~1"=="clean" GOTO clean
IF "%~1"=="cc" GOTO cc
IF "%~1"=="distclean" GOTO distclean
GOTO error

:cmake_sdk
set TOKEN_SDK=-DJVX_RELEASE_SDK=TRUE 
set JVX_GENERATOR_TOKEN=%JVX_GENERATOR_TOKEN_SDK%
set JVX_GENERATOR_ARCHITECTURE=%JVX_GENERATOR_ARCHITECTURE_SDK%
set ADDITIONAL_FEATURE_TOKENS=^
	%ADDITIONAL_FEATURE_TOKENS_MIN% ^
	%ADDITIONAL_FEATURE_TOKENS_FULL%
goto endswitch
:cmake_sdk_bt
set TOKEN_SDK=-DJVX_RELEASE_SDK=TRUE 
set TOKEN_BTOOLS=-DJVX_COMPILE_BUILDTOOLS=TRUE
set JVX_GENERATOR_TOKEN=%JVX_GENERATOR_TOKEN_BT%
set JVX_GENERATOR_ARCHITECTURE=%JVX_GENERATOR_ARCHITECTURE_BT%
set ADDITIONAL_FEATURE_TOKENS=^
	%ADDITIONAL_FEATURE_TOKENS_MIN% 
goto endswitch
:cmake_rt_bt
set TOKEN_SDK=-DJVX_RELEASE_SDK=FALSE 
set TOKEN_BTOOLS=-DJVX_COMPILE_BUILDTOOLS=TRUE
set JVX_GENERATOR_TOKEN=%JVX_GENERATOR_TOKEN_BT%
set JVX_GENERATOR_ARCHITECTURE=%JVX_GENERATOR_ARCHITECTURE_BT%
set ADDITIONAL_FEATURE_TOKENS=^
	%ADDITIONAL_FEATURE_TOKENS_MIN% 	
goto endswitch
:cmake_rt
set JVX_GENERATOR_TOKEN=%JVX_GENERATOR_TOKEN_RT%
set JVX_GENERATOR_ARCHITECTURE=%JVX_GENERATOR_ARCHITECTURE_RT%
set ADDITIONAL_FEATURE_TOKENS=^
	%ADDITIONAL_FEATURE_TOKENS_MIN% ^
	%ADDITIONAL_FEATURE_TOKENS_FULL%
:endswitch

echo cmake -DCMAKE_BUILD_TYPE=%JVX_RELEASE_TYPE% %JVX_SRC_PATH% ^
  -G %JVX_GENERATOR_TOKEN% %JVX_GENERATOR_ARCHITECTURE% ^
  -Wno-dev -DJVX_DEPLOY_UNSTABLE=TRUE ^
  -DCMAKE_INSTALL_PREFIX=release ^
  -DJVX_PRODUCT=audio ^
  -DJVX_USE_PART_ASIO=TRUE  ^
  -DJVX_USE_PART_PAUDIO=TRUE ^
  -DJVX_USE_PART_RS232=TRUE ^
  -DJVX_USE_QT=TRUE ^
  -DJVX_USE_QWT=TRUE ^
  -DJVX_USE_QWT_POLAR=TRUE ^
  -DJVX_USE_PART_CORECONTROL=TRUE ^
  %TOKEN_SDK% ^
  -DJVX_DEFINE_NUMBER_32BIT_TOKENS_BITFIELD=16 ^
  %TOKEN_BTOOLS% ^
  %ADDITIONAL_FEATURE_TOKENS% ^
  -DJVX_DEPLOY_LIBRARY_DSP_MATLAB=TRUE 
  
cmake -DCMAKE_BUILD_TYPE=%JVX_RELEASE_TYPE% %JVX_SRC_PATH% ^
  -G %JVX_GENERATOR_TOKEN% %JVX_GENERATOR_ARCHITECTURE% ^
  -Wno-dev -DJVX_DEPLOY_UNSTABLE=TRUE ^
  -DCMAKE_INSTALL_PREFIX=release ^
  -DJVX_PRODUCT=audio ^
  -DJVX_USE_PART_ASIO=TRUE  ^
  -DJVX_USE_PART_PAUDIO=TRUE ^
  -DJVX_USE_PART_RS232=TRUE ^
  -DJVX_USE_QT=TRUE ^
  -DJVX_USE_QWT=TRUE ^
  -DJVX_USE_QWT_POLAR=TRUE ^
  -DJVX_USE_PART_CORECONTROL=TRUE ^
  %TOKEN_SDK% ^
  -DJVX_DEFINE_NUMBER_32BIT_TOKENS_BITFIELD=16 ^
  %TOKEN_BTOOLS% ^
  %ADDITIONAL_FEATURE_TOKENS% ^
  -DJVX_DEPLOY_LIBRARY_DSP_MATLAB=TRUE 

  REM -DJVX_SYSTEM_USE_DATA_FORMAT_FLOAT=TRUE ^
  REM jom clean
if %JVX_GENERATOR_TOKEN% == "NMake Makefiles"  jom /J 9 install
if %JVX_GENERATOR_TOKEN% == "Ninja"  ninja install

goto end

:distclean
rmdir release /s /q  >nul 2>&1

:clean
del cmake_install.cmake >nul 2>&1
del Makefile >nul 2>&1
del install_manifest_release.txt >nul 2>&1
del install_manifest*.txt >nul 2>&1
del jvx_dsp_base.h >nul 2>&1
del octave.lib >nul 2>&1
del octinterp.lib >nul 2>&1
del *.vcxproj >nul 2>&1
del *.vcxproj.filters >nul 2>&1
del *.vcxproj.user >nul 2>&1
del *.sln >nul 2>&1
del *.VC.db >nul 2>&1
del rules.ninja >nul 2>&1
del build.ninja >nul 2>&1
del .ninja_deps >nul 2>&1
del .ninja_log >nul 2>&1
del CMakeDoxyfile.* >nul 2>&1
del CMakeDoxygenDefaults.* >nul 2>&1
del CPack* >nul 2>&1

rmdir sources /s /q  >nul 2>&1
rmdir sub-projects /s /q  >nul 2>&1
rmdir bin /s /q  >nul 2>&1
rmdir lib /s /q  >nul 2>&1
rmdir cmake /s /q  >nul 2>&1
rmdir CMakeFiles /s /q  >nul 2>&1
rmdir VST3 /s /q  >nul 2>&1
rmdir x64 /s /q  >nul 2>&1
rmdir .vs /s /q  >nul 2>&1
rmdir WIN_PDB64 /s /q  >nul 2>&1

:cc
del CMakeCache.txt >nul 2>&1

goto end

:error
echo Usage: compile ^< rt-bt ^| rt ^| sdk-bt ^| sdk ^| clean ^| distclean ^> 
:end
