#ifndef __FLUTTER_NATIVE_MACROS_H__
#define __FLUTTER_NATIVE_MACROS_H__

#ifdef JVX_DEFINE_EXTERN_C_API
#define JVX_OPTIONAL_EXTERN_C_START extern "C" {}
#define JVX_OPTIONAL_EXTERN_C_STOP }

#else

#define JVX_OPTIONAL_EXTERN_C_START
#define JVX_OPTIONAL_EXTERN_C_STOP
#endif

#endif
