function [hObject, handles] = jvx_refresh_props_run(hObject, handles, onStart, props_tech, props_dev)

handles.jvx_struct.properties.technology.id_file_progress = -1;
handles.jvx_struct.properties.technology.id_file_fwd = -1;
handles.jvx_struct.properties.technology.id_file_bwd = -1;
handles.jvx_struct.properties.technology.id_file_pause = -1;
handles.jvx_struct.properties.technology.id_file_play = -1;
handles.jvx_struct.properties.technology.id_file_restart = -1;

handles.jvx_struct.properties.technology.id_dev_load = -1;
        
handles.jvx_struct.isRunning = false;
if(onStart)
    handles.jvx_struct.isRunning = true;
    [handles.jvx_struct.properties.technology.id_file_progress, ...
        handles.jvx_struct.properties.technology.cat_file_progress, ...
        handles.jvx_struct.properties.technology.tp_file_progress] = ...
        jvxJvxHost.jvx_find_property_id_descriptor(props_tech, '/properties_selected_input_file/progress');
    [handles.jvx_struct.properties.technology.id_file_fwd, ...
        handles.jvx_struct.properties.technology.cat_file_fwd, ...
        handles.jvx_struct.properties.technology.tp_file_fwd] = ...
        jvxJvxHost.jvx_find_property_id_descriptor(props_tech, '/properties_selected_input_file/triggerFwd');
    [handles.jvx_struct.properties.technology.id_file_bwd, ...
        handles.jvx_struct.properties.technology.cat_file_bwd, ...
        handles.jvx_struct.properties.technology.tp_file_bwd] = ...
        jvxJvxHost.jvx_find_property_id_descriptor(props_tech, '/properties_selected_input_file/triggerBwd');
    [handles.jvx_struct.properties.technology.id_file_pause, ...
        handles.jvx_struct.properties.technology.cat_file_pause, ...
        handles.jvx_struct.properties.technology.tp_file_pause] = ...
        jvxJvxHost.jvx_find_property_id_descriptor(props_tech, '/properties_selected_input_file/triggerPause');
    [handles.jvx_struct.properties.technology.id_file_play, ...
        handles.jvx_struct.properties.technology.cat_file_play, ...
        handles.jvx_struct.properties.technology.tp_file_play] = ...
        jvxJvxHost.jvx_find_property_id_descriptor(props_tech, '/properties_selected_input_file/triggerPlay');
    [handles.jvx_struct.properties.technology.id_file_restart, ...
        handles.jvx_struct.properties.technology.cat_file_restart, ...
        handles.jvx_struct.properties.technology.tp_file_restart] = ...
        jvxJvxHost.jvx_find_property_id_descriptor(props_tech, '/properties_selected_input_file/triggerRestart');

    [handles.jvx_struct.properties.device.id_dev_load, ...
        handles.jvx_struct.properties.device.cat_dev_load, ...
        handles.jvx_struct.properties.device.tp_dev_load] = jvxJvxHost.jvx_find_property_id_descriptor(props_dev, '/JVX_GENW_DEV_LOAD');
end
