#ifndef __CJVXDATACONNECTIONSGROUP_TYPES_H__
#define __CJVXDATACONNECTIONSGROUP_TYPES_H__

typedef enum
{
	JVX_DATACONNECTION_GROUP_IO_CONNECTOR_UNKNOWN = 0,
	JVX_DATACONNECTION_GROUP_IO_CONNECTOR_TO_OUTSIDE = 1,
	JVX_DATACONNECTION_GROUP_IO_CONNECTOR_TO_INSIDE = 2,
	JVX_DATACONNECTION_GROUP_IO_CONNECTOR_CONNECT = 3
} jvxCjvxDataConnectionsConnectorType;

#endif

