name: AudioYoFloNative
description: Bindings to allow access to fernlive native backend.
output: 'lib/native-ffi/generated/ayf_ffi_gen_bind.dart'
headers:
  entry-points:
    - 'O:/audyoflo/audio-win64-sdk/release/sdk/include/jvx-flutter-native-static/include/flutter_native_api.h'
compiler-opts:
  "-DJVX_REDEFINE_DATATYPES_FFI -DJVX_SYS_WINDOWS_MSVC_64BIT"
enums:
  as-int:
    include:
      - ffiCallbackIds
      - ffiDeleteDatatype
type-map:
  'native-types': # Targets native types.
    'size_t':
      'lib': 'pkg_ffi' # predefined import.
      'c-type': 'size_t'
      'dart-type': 'Int64'
    'jvxCBitField':
      'lib': 'pkg_ffi' # predefined import.
      'c-type': 'jvxCBitField'
      'dart-type': 'Uint64'    
    'jvxCBitField64':
      'lib': 'pkg_ffi' # predefined import.
      'c-type': 'jvxCBitField64'
      'dart-type': 'Uint64'    
    'jvxCBitField32':
      'lib': 'pkg_ffi' # predefined import.
      'c-type': 'jvxCBitField32'
      'dart-type': 'Uint32'    
    'jvxCBitField16':
      'lib': 'pkg_ffi' # predefined import.
      'c-type': 'jvxCBitField16'
      'dart-type': 'Uint16'    
    'jvxSize':
      'lib': 'pkg_ffi' # predefined import.
      'c-type': 'jvxSize'
      'dart-type': 'Uint64'    
    'jvxInt32':
      'lib': 'pkg_ffi' # predefined import.
      'c-type': 'jvxInt32'
      'dart-type': 'Int32'    
    'jvxInt64':
      'lib': 'pkg_ffi' # predefined import.
      'c-type': 'jvxSize'
      'dart-type': 'Int64'          
