name: ayf_ffihost
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  collection: ^1.16.0

  # path_provider: ^2.1.5
  
  ayf_pack:
    path: '../ayf_pack'

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.0

  ffigen: ^18.0.1

# This is the command to specify which file is source for binding generation
## ============================================================================
## For ffigen: run command <dart run ffigen --config config.yaml>
## However, due to an unsufficiency of the code generator, we need to rename some variables starting
## around line 1401:
## 
## typedef jvxSize = ffi.Size;
# typedef DartjvxSize = int;
## typedef jvxCBitField64 = ffi.UnsignedLongLong;
## typedef DartjvxCBitField64 = int;
## typedef jvxCBitField32 = ffi.UnsignedInt;
## typedef DartjvxCBitField32 = int;
## typedef jvxCBitField16 = ffi.UnsignedShort;
## typedef DartjvxCBitField16 = int;
## typedef jvxInt64 = ffi.LongLong;
## typedef DartjvxInt64 = int;
## typedef jvxUInt64 = ffi.UnsignedLongLong;
## typedef DartjvxUInt64 = int;
## typedef jvxInt32 = ffi.Int;
## typedef DartjvxInt32 = int;
## typedef jvxUInt32 = ffi.UnsignedInt;
## typedef DartjvxUInt32 = int;
## typedef jvxInt16 = ffi.Short;
## typedef DartjvxInt16 = int;
## typedef jvxUInt16 = ffi.UnsignedShort;
## typedef DartjvxUInt16 = int;

## to
##
## typedef jvxSize = ffi.Size;
## typedef jvxCBitField64 = ffi.Uint64;
## typedef jvxCBitField32 = ffi.Uint32;
## typedef jvxCBitField16 = ffi.Uint16;
## typedef jvxInt64 = ffi.Int64;
## typedef jvxUInt64 = ffi.Uint64;
## typedef jvxInt32 = ffi.Int32;
## typedef jvxUInt32 = ffi.Uint32;
## typedef jvxInt16 = ffi.Int16;
## typedef jvxUInt16 = ffi.Uint16;
## Replacement is in file <replace-datatypes.txt>
##
## Anomalie/insufficiency of code generator reported here:
##
## https://github.com/dart-lang/native/issues/2297
##
## ============================================================================

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
