# Select host to be loaded
EMBEDDED_HOST=MIN
# EMBEDDED_HOST=EMB
# EMBEDDED_HOST=NONE

# Define the name of the min host to be loaded
DLL_MIN_HOST=ayf-shared-connection-min-host.dll
DLL_EMB_HOST=ayf-shared-connection-full-host.dll

DLL_EMB_ARG=--config,jvxConfig.jvx,--textlog,--verbose_dll,--textloglev,10

# Attach a new console window to review runtime output
OPEN_CONSOLE=yes
