enum jvxWebHostOperationResponseType {
  JVX_RESPONSE_INIT_CONNECT,
  JVX_MESSAGE_WEBSOCKET
}

enum jvxWebHostConnectionState {
  JVX_CONECTION_NONE,
  JVX_CONECTION_FIRST_CONTACT_DONE,
  JVX_CONECTION_WEBSOCKET_ON,
  JVX_CONECTION_FULL_STATE_TRANSMITTED_OK
}
