#ifdef JVX_INCLUDE_COMPONENTS
,JVX_COMPONENT_RT_AUDIO_FILE_READER
,JVX_COMPONENT_RT_AUDIO_FILE_WRITER
,JVX_COMPONENT_RESAMPLER
,JVX_COMPONENT_DATACONVERTER
#endif

#ifdef JVX_INCLUDE_CLASSES
, { jvxComponentTypeClass::JVX_COMPONENT_TYPE_TOOL, JVX_COMPONENT_UNKNOWN, NULL, NULL , NULL }
, { jvxComponentTypeClass::JVX_COMPONENT_TYPE_TOOL, JVX_COMPONENT_UNKNOWN, NULL, NULL, NULL }
, { jvxComponentTypeClass::JVX_COMPONENT_TYPE_TOOL, JVX_COMPONENT_UNKNOWN, NULL, NULL, NULL }
, { jvxComponentTypeClass::JVX_COMPONENT_TYPE_TOOL, JVX_COMPONENT_UNKNOWN, NULL, NULL, NULL }
#endif
