#ifndef __TPJVXTYPES_DATAGROUPS_H__
#define __TPJVXTYPES_DATAGROUPS_H__

#define JVX_DATAFORMAT_GROUP_DEFINES_PRODUCT \
	,JVX_DATAFORMAT_GROUP_AUDIO_PDM \
	,JVX_DATAFORMAT_GROUP_AUDIO_CODED_GENERIC \
	,JVX_DATAFORMAT_GROUP_AUDIO_CODED_OPUS_NO_CONTAINER \
	,JVX_DATAFORMAT_GROUP_AUDIO_PCM_HOA \
	,JVX_DATAFORMAT_GROUP_AUDIO_PCM_DIRECTIONS 
	
#define JVX_DATAFORMAT_GROUP_STRINGS_PRODUCT \
	,{"audio pdm", "JVX_DATAFORMAT_GROUP_AUDIO_PDM" } \
	,{"audio coded generic", "JVX_DATAFORMAT_GROUP_AUDIO_CODED_GENERIC"} \
	,{"audio coded opus", "JVX_DATAFORMAT_GROUP_AUDIO_CODED_OPUS_NO_CONTAINER"} \
	,{"audio pcm hoa", "JVX_DATAFORMAT_GROUP_AUDIO_PCM_HOA"} \
	,{"audio pcm directions", "JVX_DATAFORMAT_GROUP_AUDIO_PCM_DIRECTIONS" }

	
	#define JVX_DATAFORMAT_GROUP_SIZES_PRODUCT \
	, 1 /* JVX_DATAFORMAT_GROUP_AUDIO_PDM */ \
	, 0 /* JVX_DATAFORMAT_GROUP_AUDIO_CODED_GENERIC */ \
	, 0 /* JVX_DATAFORMAT_GROUP_AUDIO_CODED_OPUS_NO_CONTAINER */ \
	, 1 /* JVX_DATAFORMAT_GROUP_AUDIO_PCM_HOA */ \
	, 1 /* JVX_DATAFORMAT_GROUP_AUDIO_PCM_DIRECTIONS */
	
#endif