#ifdef JVX_INCLUDE_COMPONENTS
,JVX_COMPONENT_AUDIO_CODEC
,JVX_COMPONENT_AUDIO_ENCODER
,JVX_COMPONENT_AUDIO_DECODER
#endif

#ifdef JVX_INCLUDE_CLASSES
, { jvxComponentTypeClass::JVX_COMPONENT_TYPE_CODEC, JVX_COMPONENT_UNKNOWN, NULL, NULL, NULL, jvxComponentTypeClass::JVX_COMPONENT_TYPE_NONE }
, { jvxComponentTypeClass::JVX_COMPONENT_TYPE_CODEC, JVX_COMPONENT_UNKNOWN, NULL, NULL, NULL, jvxComponentTypeClass::JVX_COMPONENT_TYPE_NONE }
, { jvxComponentTypeClass::JVX_COMPONENT_TYPE_CODEC, JVX_COMPONENT_UNKNOWN, NULL, NULL, NULL, jvxComponentTypeClass::JVX_COMPONENT_TYPE_NONE }
#endif