#ifndef _JVXSPECIALCHARACTERDEFINES_H__
#define _JVXSPECIALCHARACTERDEFINES_H__

#define JVX_CHARACTER_INPUT_ONE_LINE_TTY_V1 '\r'
#define JVX_CHARACTER_START_SPECIAL_CHAR_V1 224
#define JVX_CHARACTER_REMOVE_SPECIAL_CHAR_NUM_V1 0
#define JVX_CHARACTER_SPECIAL_CHAR_CTRLC 0x3

#define JVX_CHARACTER_INPUT_ONE_LINE_TTY_V2 '\n'
#define JVX_CHARACTER_START_SPECIAL_CHAR_V2 27
#define JVX_CHARACTER_REMOVE_SPECIAL_CHAR_NUM_V2 1


#ifdef JVX_CONSOLE_KEYMAP_V1
#define JVX_CHARACTER_REMOVE_LAST_TTY '\b'
#define JVX_ASCI_CODE_ARROW_UP_TTY 72
#define JVX_ASCI_CODE_ARROW_DOWN_TTY 80
#define JVX_ASCI_CODE_ARROW_LEFT_TTY 75
#define JVX_ASCI_CODE_ARROW_RIGHT_TTY 77
#define JVX_ASCI_CODE_DELETE_TTY 83
#define JVX_ASCI_CODE_BEGINLINE_TTY 71
#define JVX_ASCI_CODE_ENDLINE_TTY 79
 
#else

#define JVX_CHARACTER_REMOVE_LAST_TTY 0x7F
#define JVX_ASCI_CODE_ARROW_UP_TTY 65
#define JVX_ASCI_CODE_ARROW_DOWN_TTY 66
#define JVX_ASCI_CODE_ARROW_LEFT_TTY 68
#define JVX_ASCI_CODE_ARROW_RIGHT_TTY 67
#define JVX_ASCI_CODE_BEGINLINE_TTY 72
#define JVX_ASCI_CODE_ENDLINE_TTY 70
#define JVX_ASCI_CODE_DELETE_TTY 126

#endif

#endif
