#ifndef __JVX_BASE_DSP_TYPES_LINUX_H__
#define __JVX_BASE_DSP_TYPES_LINUX_H__

#include <stddef.h>
#include <inttypes.h>
#include <limits.h>
#include <stdio.h>
#include <string.h>
#include <math.h>
#include <assert.h>

//! Size datatype to be used within RTProc
typedef size_t jvxSize;

//! 8 Bit = 1 Byte datatype
typedef char jvxByte;

//! 8 Bit = 1 Byte datatype
typedef unsigned char jvxUByte;

//! Conventional 32 bit data with sign
typedef int32_t jvxInt32;

//! Conventional 32 bit data without sign
typedef uint32_t jvxUInt32;

//! Signed 16 bit datatype
typedef int16_t jvxInt16;

//! Signed 16 bit datatype
typedef uint16_t jvxSize16;

//! Unsigned 16 bit datatype
typedef uint16_t jvxUInt16;

//! Signed 64 bit datatype
typedef int64_t jvxInt64;

//! Unsigned 64 bit datatype
typedef uint64_t jvxUInt64;

//! Signed 8 bit datatype
typedef int8_t jvxInt8;

//! Unsigned 8 bit datatype
typedef uint8_t jvxUInt8;

//! Double precision floatdata format (64 bit float)
//typedef double jvxDouble;

//! Single precision floatdata format (64 bit float)
//typedef float jvxFloat;

//! Bool variable
#ifdef __cplusplus
typedef bool jvxBool;
typedef jvxUInt16 jvxCBool;
#define c_true 1
#define c_false 0
#else
typedef jvxUInt16 jvxCBool;
#define true 1
#define false 0
#define c_true 1
#define c_false 0
#endif

#define JVX_SIZET_SIZE(var) var 
#define JVX_SIZE_SIZET(var) var 

#define JVX_RESTRICT /*__restrict*/
#define JVX_STATIC_INLINE inline

//! Variable type for every unspecific data types.
typedef void jvxHandle;

//! Unsigned 64 bit datatype
typedef uint64_t jvxCBitField;

//! Typedef enums for error types
typedef enum
{
	// General error codes used at different positions
	RTP_ERROR_NO_ERROR = 0,
	RTP_ERROR_INTERNAL,
	RTP_ERROR_NOT_READY,
	RTP_ERROR_NOT_COMPATIBLE,
	RTP_ERROR_WRONG_STATE_FOR_CALL,
	RTP_ERROR_ID_NOT_VALID,
	RTP_ERROR_VOID_DATA_SIZE_MISMATCH,
	RTP_ERROR_ELEMENT_NOT_FOUND,
	RTP_ERROR_OPERATION_NOT_SUPPORTED,
	RTP_ERROR_UNEXPECTED,
	RTP_ERROR_NOT_PERMITTED,
	RTP_ERROR_MISC,
	RTP_ERROR_MATLAB,
	RTP_ERROR_TIMEOUT_EXPIRED,
	RTP_ERROR_INTERFACE_NOT_SUPPORTED,
	RTP_ERROR_INVALID_POINTER,
	RTP_ERROR_INVALID_ARGUMENT,
	RTP_ERROR_STANDARD_EXCEPTION,

	// Processing environment errors
	RTP_ERROR_PROCESSING_ENVIRONMENT_NOT_SUPPORTED,
	RTP_ERROR_PROCESSING_ENVIRONMENT_WRONG_OUTPUT_PARAMETER,
	RTP_ERROR_PROCESSING_ENVIRONMENT_WRONG_INPUT_PARAMETER,

	// Audio processing environment errors
	RTP_ERROR_AUDIO_PROCESSING_ENVIRONMENT_WRONG_OUTPUT_PARAMETER,
	RTP_ERROR_AUDIO_PROCESSING_ENVIRONMENT_WRONG_INPUT_PARAMETER,
	RTP_ERROR_AUDIO_PROCESSING_ENVIRONMENT_LISTENER_REGISTERED_BEFORE,
	RTP_ERROR_AUDIO_PROCESSING_ENVIRONMENT_LISTENER_NOT_REGISTERED_BEFORE,
	RTP_ERROR_AUDIO_PROCESSING_ENVIRONMENT_WRONG_STATE_FOR_CALL,
	RTP_ERROR_AUDIO_PROCESSING_ENVIRONMENT_IS_LOCKED,
	RTP_ERROR_AUDIO_PROCESSING_ENVIRONMENT_NO_CHANNELS_LEFT_TO_RELEASE,
	RTP_ERROR_AUDIO_PROCESSING_ENVIRONMENT_ID_OUT_OF_SCOPE,

	// Buffering errors
	RTP_ERROR_BUFFERING_FORMAT_NOT_SUPPORTED,
	RTP_ERROR_BUFFERING_WRONG_STATE,
	RTP_ERROR_BUFFERING_TOO_MANY_SAMPLES_INPUT,
	RTP_ERROR_BUFFERING_INPUT_OUTPUT_OVERLAP,
	RTP_ERROR_BUFFERING_INVALID_ARGUMENT,
	RTP_ERROR_BUFFERING_OVEFLOW,

	// File input/output errors
	RTP_ERROR_FILEIO_OPEN_FILE_FAILED,
	RTP_ERROR_FILEIO_OPEN_FILE_INTEGRITY,
	RTP_ERROR_FILEIO_OPEN_NO_FILE_SELECTED ,
	RTP_ERROR_FILEIO_OPEN_END_OF_SESSION,
	RTP_ERROR_FILEIO_DATASET_ID_COPY,
	RTP_ERROR_FILEIO_TIMING_WARNING,
	RTP_ERROR_FILEIO_BUFFER_OVERFLOW,
	RTP_ERROR_FILEIO_FILE_WRITER_BUSY,

	// Remote call errors
	RTP_ERROR_REMOTE_CALL_CONNECTION_CALL_TIMEOUT,
	RTP_ERROR_REMOTE_CALL_CONNECTION_NOT_CONNECTED,
	RTP_ERROR_REMOTE_CALL_CONNECTION_CALL_IN_PROGRESS,
	RTP_ERROR_REMOTE_CALL_CONNECTION_REJECT_ACTION,
	RTP_ERROR_REMOTE_CALL_CONNECTION_ABORTED_BY_OTHER_SIDE,
	RTP_ERROR_REMOTE_CALL_CONNECTION_SIZE_MISMATCH,
	RTP_ERROR_REMOTE_CALL_CONNECTION_NUM_PARAMETERS_IN,
	RTP_ERROR_REMOTE_CALL_CONNECTION_NUM_PARAMETERS_OUT,
	RTP_ERROR_REMOTE_CALL_CONNECTION_WRONG_STATE,
	RTP_ERROR_REMOTE_CALL_CONNECTION_WRONG_PROCESS_COUNTER,
	RTP_ERROR_REMOTE_CALL_CONNECTION_NUM_PARAMS_INCOMPLETE,
	RTP_ERROR_REMOTE_CALL_CONNECTION_ACTION_FAILED_OTHER_SIDE,
	RTP_ERROR_REMOTE_CALL_CONNECTION_OTHER_SIDE_OFFSET,
	RTP_ERROR_REMOTE_CALL_CONNECTION_ACTION_LOCKED,
	RTP_ERROR_REMOTE_CALL_CONNECTION_ACTION_NOT_LOCKED,
	RTP_ERROR_REMOTE_CALL_CONNECTION_NO_TRIGGER_EVENT,
	RTP_ERROR_REMOTE_CALL_CONNECTION_NO_RETURN_CODE,
	RTP_ERROR_REMOTE_CALL_PARSE_ERROR,

	// RS232 errors
	RTP_ERROR_RS232_ID_RECEIVE_BUFFER_FULL,
	RTP_ERROR_RS232_ID_SEND_BUFFER_FULL,
	RTP_ERROR_RS232_SEND_FAILED,
	RTP_ERROR_RS232_FAILED_SCAN_PORTS,
	RTP_ERROR_RS232_FAILED_OPEN_PORT,
	RTP_ERROR_RS232_FAILED_ACTIVATE_PORT,
	RTP_ERROR_RS232_FAILED_CLOSE_PORT,
	RTP_ERROR_RS232_FAILED_DEACTIVATE_PORT,
	RTP_ERROR_RS232_INIT_SEND_FAILED,
	RTP_ERROR_RS232_SET_STOP_MODE_FAILED,
	RTP_ERROR_RS232_SET_STOP_MODE_FIELD_LENGTH_FAILED,
	RTP_ERROR_RS232_SET_STOP_MODE_CHARACTER_FAILED,
	RTP_ERROR_RS232_GET_CTS_FAILED,
	RTP_ERROR_RS232_GET_DSR_FAILED,
	RTP_ERROR_RS232_GET_RING_FAILED,
	RTP_ERROR_RS232_GET_RLSD_FAILED,
	RTP_ERROR_RS232_SOCKET_CREATE_FAILED,
	RTP_ERROR_RS232_SOCKET_SETCOMMSTATE_FAILED,

	// Error related to configurtion handling
	RTP_ERROR_CONFIGURATION_INPUT_NOT_ACCEPTED,
	RTP_ERROR_CONFIGURATION_OUTPUT_NOT_PRODUCED,

	// Errors related to use of configProcessor
	RTP_ERROR_CONFIG_PROCESSOR_PARSE_ERROR,
	RTP_ERROR_CONFIG_PROCESSOR_FILE_DOES_NOT_EXIST,
	RTP_ERROR_CONFIG_PROCESSOR_WRONG_SECTION_TYPE,
	RTP_ERROR_CONFIG_PROCESSOR_EMPTY_LIST,

	// Error codes related to external (Matlab) calls
	RTP_ERROR_EXTERNAL_CALL_NUMBER_INPUT_PARAMETERS,
	RTP_ERROR_EXTERNAL_CALL_NUMBER_OUTPUT_PARAMETERS,
	RTP_ERROR_EXTERNAL_CALL_TYPE_INPUT_VARIABLE,
	RTP_ERROR_EXTERNAL_CALL_ZERO_SIZE_INPUT_VARIABLE,
	RTP_ERROR_EXTERNAL_CALL_INTERNAL,
	RTP_ERROR_EXTERNAL_CALL_FUNCTION_NOT_FOUND,
	RTP_ERROR_EXTERNAL_CALL_WRONG_NUMBER_PARAMETER,
	RTP_ERROR_EXTERNAL_CALL_FUNCTION_REGISTERED_BEFORE,
	RTP_ERROR_EXTERNAL_CALL_WRONG_THREAD,
	RTP_ERROR_EXTERNAL_CALL_WRONG_DATAFORMAT,
	RTP_ERROR_EXTERNAL_CALL_WRONG_NUMBER_COLUMNS,
	RTP_ERROR_EXTERNAL_CALL_WRONG_NUMBER_ROWS,
	RTP_ERROR_EXTERNAL_CALL_COMMAND_FAILED,
	RTP_ERROR_EXTERNAL_CALL_PUT_VARIABLE_FAILED,
	RTP_ERROR_EXTERNAL_CALL_GET_VARIABLE_FAILED,

	// Error codes related to codecs
	RTP_ERROR_CODEC_NO_DATA_CONSUMED,
	RTP_ERROR_CODEC_NO_CHANNEL_CONSUMED,
	RTP_ERROR_CODEC_UNEXPECTED_PACKAGE,
	RTP_ERROR_CODEC_UNKNOWN_FORMAT,

	// Error related to runtime messages
	RTP_ERROR_RUNTIME_MESSAGE_MESSAGE_QUEUE_NOT_SUPPORTED,
	RTP_ERROR_RUNTIME_MESSAGES_QUEUE_NOT_SUPPORTED,
	RTP_ERROR_RUNTIME_MESSAGES_MESSAGE_QUEUE_BUSY,
	RTP_ERROR_RUNTIME_MESSAGES_MESSAGE_QUEUE_FULL,
	RTP_ERROR_RUNTIME_MESSAGES_MESSAGE_QUEUE_EMPTY,
	RTP_ERROR_RUNTIME_MESSAGES_MESSAGE_QUEUE_INVALID_CONTENT,
	RTP_ERROR_RUNTIME_MESSAGE_FAILED_TO_ADD,

	// Errors related to sockets
	RTP_ERROR_SOCKET_MESSAGE_STREAMING_TOO_LONG,
	RTP_ERROR_SOCKET_STREAMING_QUEUE_FULL,

	// Errors related to netscheduler
	RTP_ERROR_NETSCHEDULER_CONNECT_FAILED,

	// Errors related to use of factories
	RTP_ERROR_FACTORY_LIBRARY_ADDED_BEFORE,
	RTP_ERROR_FACTORY_LIBRARY_LOCKED,

	// Errors related to window manager
	RTP_ERROR_QT_WINDOW_MANAGER_NOT_TERMINATED_PROPPERLY,

	// Errors related to remote commands
	RTP_ERROR_REMOTE_COMMAND_PARSE_ERROR,
	RTP_ERROR_REMOTE_COMMAND_WRONG_TYPE,


	// Circular buffering error codes
	RTP_ERROR_CIRCULAR_BUFFER_OVERFLOW,
	RTP_ERROR_CIRCULAR_BUFFER_UNDERFLOW,

	// Specific error code for generic wrapper
	RTP_ERROR_CHANNEL_ALREADY_RESERVED,

	// Host error mesages common to all hosts
	RTP_ERROR_HOST_INTERFACE_FACTORY_FAILED,

	// Matlab specific error codes
	RTP_ERROR_MATLAB_HOST_EXCEPTION,
	RTP_ERROR_MATLAB_HOST_STANDARD_EXCEPTION,
	RTP_ERROR_MATLAB_HOST_UNKNOWN_TEXT_COMMAND,
	RTP_ERROR_MATLAB_HOST_WRONG_FORMAT_COMMAND_ARGUMENT,
	RTP_ERROR_MATLAB_HOST_WRONG_UNKNWON_COMMAND_ARGUMENT,
	RTP_ERROR_MATLAB_HOST_NO_ALGORITHM_SELECTED,
	RTP_ERROR_MATLAB_HOST_NO_TECHNOLOGY_SELECTED,
	RTP_ERROR_MATLAB_HOST_NO_DEVICE_SELECTED,
	RTP_ERROR_MATLAB_HOST_FILL_GENERIC_TEMPLATE,
	RTP_ERROR_MATLAB_HOST_WRONG_NUMBER_ARGUMENTS,
	RTP_ERROR_MATLAB_HOST_WRONG_FORMAT_ARGUMENT,
	RTP_ERROR_MATLAB_HOST_EXTERNAL_HOOK_ERROR,
	RTP_ERROR_MATLAB_HOST_WRONG_DATATYPE_CALL,
	RTP_ERROR_MATLAB_HOST_ARGUMENT_MISMATCH,
	RTP_ERROR_MATLAB_HOST_ARGUMENT_INVALID_ID,
	RTP_ERROR_MATLAB_HOST_UNSUPPORTED_DATATYPE,
	RTP_ERROR_MATLAB_HOST_ZERO_COPY,

	// Generic host specific errorcodes
	RTP_ERROR_GENERIC_HOST_NO_CONFIG_PROCESSOR

} rtpErrorType;

/*
extern void report_event(const char* errtext, jvxInt32 errid);

static inline void JVX_ASSERT(const char* errtext, jvxInt32 errid, jvxCBool condition)
{
	if(!condition)
	{
		report_event(errtext, errid);
		assert(0);
	}
}
*/

#endif

