#ifndef JVX_AUDIO_CONFIG_H__
#define JVX_AUDIO_CONFIG_H__

// Define to activate line in audio, MAKE SURE HARDWARE IS CONNECTED!!!
//#define JVX_AUDIO_LINE_IO

#define JVX_IO_TEMP_BUFFER
#ifdef JVX_AUDIO_LINE_IO

#define JVX_SAMPLERATE_IN 48000
#define JVX_BUFFERSIZE_IN 256
#define JVX_BUFFERSIZE_OUT JVX_BUFFERSIZE_IN
#define JVX_SAMPLERATE_OUT JVX_SAMPLERATE_IN
#else

// 192 kHz in, 48 kHz out
#define JVX_SAMPLERATE_IN 96000
#define JVX_BUFFERSIZE_IN 256
#define JVX_BUFFERSIZE_OUT 128
#define JVX_SAMPLERATE_OUT 48000

// 96 kHz in, 48 kHz out
//#define JVX_SAMPLERATE_IN 48000
//#define JVX_BUFFERSIZE_IN 256
//#define JVX_BUFFERSIZE_OUT 256
//#define JVX_SAMPLERATE_OUT 48000

// Following works for 48 kHz processing
//#define JVX_SAMPLERATE_IN 24000
//#define JVX_BUFFERSIZE_IN 128
//#define JVX_BUFFERSIZE_OUT JVX_BUFFERSIZE_IN * 2
//#define JVX_SAMPLERATE_OUT JVX_SAMPLERATE_IN * 2
#endif

#define JVX_NUMBER_CHANNELS_IN 2
#define JVX_NUMBER_CHANNELS_OUT 2
#define JVX_DATAFORMAT_PROCESSING JVX_DATAFORMAT_16BIT_LE
#define JVX_CPU_CLOCK_I 204000000

#define JVX_INTERLEAVED_BUFFERSIZE_IN (JVX_BUFFERSIZE_IN * JVX_NUMBER_CHANNELS_IN)
#define JVX_INTERLEAVED_BUFFERSIZE_OUT (JVX_BUFFERSIZE_OUT * JVX_NUMBER_CHANNELS_OUT)

#endif
