#ifndef __TJVXTRIGGERCONNECTOR_H__
#define __TJVXTRIGGERCONNECTOR_H__

enum class jvxTriggerConnectorPurpose
{
	JVX_CONNECTOR_TRIGGER_CONNECT,  /* Variable argument is the IjvxMaster* */
	JVX_CONNECTOR_TRIGGER_DISCONNECT, 
	JVX_CONNECTOR_TRIGGER_TEST,
	JVX_CONNECTOR_TRIGGER_PREPARE,
	JVX_CONNECTOR_TRIGGER_START,
	JVX_CONNECTOR_TRIGGER_STOP,
	JVX_CONNECTOR_TRIGGER_POSTPROCESS,
	JVX_CONNECTOR_TRIGGER_FORWARD, 
	JVX_CONNECTOR_TRIGGER_BACKWARD
};

#endif
