#ifndef __TJVXREPORTTEXTMESSAGE_H__
#define __TJVXREPORTTEXTMESSAGE_H__

typedef enum
{
	JVX_REPORT_PRIORITY_NONE,
	JVX_REPORT_PRIORITY_ERROR,
	JVX_REPORT_PRIORITY_WARNING,
	JVX_REPORT_PRIORITY_SUCCESS,
	JVX_REPORT_PRIORITY_INFO,
	JVX_REPORT_PRIORITY_VERBOSE,
	JVX_REPORT_PRIORITY_DEBUG,
	JVX_REPORT_PRIORITY_LIMIT
} jvxReportPriority;

typedef enum
{
	JVX_REPORT_REQUEST_UPDATE_WINDOW_SHIFT = 0,
	JVX_REPORT_REQUEST_UPDATE_PROPERTY_VIEWER_SHIFT = 1,
	JVX_REPORT_REQUEST_UPDATE_PROPERTY_VIEWER_FULL_SHIFT = 2,
	JVX_REPORT_REQUEST_TRY_TRIGGER_STOP_SEQUENCER_PROCESS_SHIFT = 3,
	JVX_REPORT_REQUEST_TRY_TRIGGER_START_SEQUENCER_SHIFT = 4,
	JVX_REPORT_REQUEST_UPDATE_DATACONNECTIONS_SHIFT_DEP = 5,
	JVX_REPORT_REQUEST_USER_MESSAGE_SHIFT = 6,
	JVX_REPORT_REQUEST_UPDATE_PROPERTIES_SHIFT_DEP = 7,
	JVX_REPORT_REQUEST_TEST_CHAIN_MASTER_SHIFT = 8,
	JVX_REPORT_REQUEST_RECONFIGURE_SHIFT = 9,
	JVX_REPORT_REQUEST_REACTIVATE_SHIFT = 10,
	JVX_REPORT_REQUEST_TRY_TRIGGER_STOP_SEQUENCER_SUBROUTINE_SHIFT = 11,
	JVX_REPORT_REQUEST_COMMAND_RETRIGGER_SEQUENCER_SHIFT_DEP = 12,
	JVX_REPORT_REQUEST_LIMIT
} jvxCommandRequestFlags;

#define JVX_REPORT_REQUEST_UPDATE_DEFAULT ((jvxCBitField)1 << JVX_REPORT_REQUEST_UPDATE_WINDOW_SHIFT)

typedef enum
{
	JVX_UPDATE_WINDOW_SHIFT = 0  /* <- this MUST BE identical to JVX_REPORT_REQUEST_UPDATE_WINDOW_SHIFT in jvxCommandRequestFlags */,
	JVX_UPDATE_PROPERTY_VIEWER_SHIFT = 1 /* <- this MUST BE identical to JVX_REPORT_REQUEST_UPDATE_PROPERTY_VIEWER_SHIFT in jvxCommandRequestFlags */,
	JVX_UPDATE_PROPERTY_VIEWER_FULL_SHIFT = 2  /* <- this MUST BE identical to JVX_REPORT_REQUEST_UPDATE_PROPERTY_VIEWER_FULL_SHIFT in jvxCommandRequestFlags */,
	JVX_UPDATE_WINDOW_SYSTEM_STATE_TRANSITION_SHIFT = 3, // Change of (local) system state
	JVX_UPDATE_WINDOW_SYSTEM_STARTUP_SHIFT = 4,  // Local System started
	JVX_UPDATE_WINDOW_SYSTEM_SHUTDOWN_SHIFT = 5, // Local system stopped
	JVX_UPDATE_WINDOW_CONFIG_READ_SHIFT = 6,
	JVX_UPDATE_WINDOW_PROPERTY_CONNECTED_SHIFT = 7,
	JVX_UPDATE_WINDOW_PROPERTY_DISCONNECTED_SHIFT = 8,
	JVX_UPDATE_WINDOW_ERROR_SHIFT = 9,
	JVX_UPDATE_WINDOW_PROPERTY_VIEWER_STARTUP_SHIFT = 10,
	JVX_UPDATE_WINDOW_PROPERTY_VIEWER_SHUTDOWN_SHIFT = 11,
	JVX_UPDATE_WINDOW_SEQ_STATE_TRANSITION_SHIFT = 12, // Report a transition of sequencer state
	JVX_UPDATE_WINDOW_SEQ_STATE_REPORT_SHIFT = 13, // Report the current sequencer state
	JVX_UPDATE_WINDOW_SYSTEM_STATE_REMOTE_TRANSISTION_SHIFT = 14, // Report system state switch in remote system (web host)
	JVX_UPDATE_WINDOW_LIMIT
} jvxUpdateWindowFlags;


#endif
