#ifndef _TJVXCIRCBUFFERDATACOLLECTOR_H__
#define _TJVXCIRCBUFFERDATACOLLECTOR_H__

typedef enum
{
	JVX_CIRCBUFFER_VISUAL_RESAMPLER = 0x1,
	JVX_CIRCBUFFER_TRIGGER_INBAND = 0x2,
	JVX_CIRCBUFFER_TRIGGER_EXPLICIT = 0x4
} jvxCircBufferDataCollectorMode;

#endif