#ifndef __CJVXWEBCONTROL_FE_PRIVATE_H__
#define __CJVXWEBCONTROL_FE_PRIVATE_H__

#define JVX_TIMOUT_BLOCKING_CALL_MSEC 50000

//#define JVX_FE_CONSOLE_VERBOSE
#define JVX_RTST_BUFFER_SIZE 128
#define JVX_WEBCONTROL_SILENT_MODE "JVX_WEBCONTROL_CONSOLE_SILENT_MODE"
#define JVX_WEBCONTROL_SECTION "JVX_WEBCONTROL_CONSOLE_SECTION"

#define JVX_EVENT_LOOP_EVENT_WS_READY (JVX_EVENTLOOP_EVENT_SPECIFIC + 1)
#define JVX_EVENT_LOOP_EVENT_WS_CLOSE (JVX_EVENTLOOP_EVENT_SPECIFIC + 2)
#define JVX_EVENT_LOOP_EVENT_WS_TIMEOUT (JVX_EVENTLOOP_EVENT_SPECIFIC + 3)
#define JVX_EVENT_LOOP_EVENT_WS_TIMEOUT_RECONF  (JVX_EVENTLOOP_EVENT_SPECIFIC + 4)
#define JVX_EVENT_LOOP_EVENT_WS_ADD_PROP_LIST  (JVX_EVENTLOOP_EVENT_SPECIFIC + 5)
#define JVX_EVENT_LOOP_EVENT_WS_REM_PROP_LIST  (JVX_EVENTLOOP_EVENT_SPECIFIC + 6)
#define JVX_EVENT_LOOP_EVENT_WS_FLOW_EVENT  (JVX_EVENTLOOP_EVENT_SPECIFIC + 7)
#define JVX_EVENT_LOOP_EVENT_WS_COMM_ERROR (JVX_EVENTLOOP_EVENT_SPECIFIC + 8)
#define JVX_EVENT_LOOP_EVENT_WS_TEXT_INPUT  (JVX_EVENTLOOP_EVENT_SPECIFIC + 9)

#define JVX_EVENTLOOP_DATAFORMAT_SPEC_JVXWEBCONTEXT (JVX_EVENTLOOP_DATAFORMAT_OFF_SPECIFIC + 1)
#define JVX_EVENTLOOP_DATAFORMAT_SPEC_JVXPROPERTYPROPERTYOBSERVEHEADER (JVX_EVENTLOOP_DATAFORMAT_OFF_SPECIFIC + 2)
#define JVX_EVENTLOOP_DATAFORMAT_SPEC_JVXPROPERTYCONFIGUREPROPERTYSEND (JVX_EVENTLOOP_DATAFORMAT_OFF_SPECIFIC + 3 )
#define JVX_EVENTLOOP_DATAFORMAT_SPEC_JVXPROPERTYPROPERTYOBSERVEHEADER_RESPONSE (JVX_EVENTLOOP_DATAFORMAT_OFF_SPECIFIC + 4 )
#define JVX_EVENTLOOP_DATAFORMAT_SPEC_JVXONEWSTEXTREQUEST (JVX_EVENTLOOP_DATAFORMAT_OFF_SPECIFIC + 5)

#define JVX_URI_BINARY_SOCKET (std::string)"/jvx/host/socket/"
#define JVX_URI_TEXT_SOCKET (std::string)"/jvx/host/ws/"

#endif
