###
# basic build settings
###

if(JVX_OBJECTS_WITH_TEXTLOG)
	set(GLOBAL_COMPILE_DEFINITIONS "${GLOBAL_COMPILE_DEFINITIONS};JVX_OBJECTS_WITH_TEXTLOG")
endif()

if(JVX_SPLASH_SUPPRESSED)
	set(GLOBAL_COMPILE_DEFINITIONS "${GLOBAL_COMPILE_DEFINITIONS};JVX_SPLASH_SUPPRESSED")
endif()

if(JVX_OPENGL_MAP_GLES2)
  set(GLOBAL_COMPILE_DEFINITIONS "${GLOBAL_COMPILE_DEFINITIONS};JVX_OPENGL_MAP_GLES2")
endif()
  
set(GLOBAL_COMPILE_DEFINITIONS "${GLOBAL_COMPILE_DEFINITIONS};JVX_QT_SPLASH_TEXT_COLOR=${JVX_QT_SPLASH_TEXT_COLOR}")

if(JVX_PROJECT_SPECIFIC_DEFINE)
  set(GLOBAL_COMPILE_DEFINITIONS "${GLOBAL_COMPILE_DEFINITIONS};${JVX_PROJECT_SPECIFIC_DEFINE}")
endif()

if(JVX_USE_OLD_CONFIG_FILE_TYPE)
	set(GLOBAL_COMPILE_DEFINITIONS "${GLOBAL_COMPILE_DEFINITIONS};JVX_STORE_CONFIG_NAME")
endif()

if(JVX_DEFINE_NUMBER_32BIT_TOKENS_BITFIELD)
	set(GLOBAL_COMPILE_DEFINITIONS "${GLOBAL_COMPILE_DEFINITIONS};JVX_NUMBER_32BITS_BITFIELD=${JVX_DEFINE_NUMBER_32BIT_TOKENS_BITFIELD}")
endif()

if(JVX_DEFAULT_NUMBER_OF_POSTPONE_ATTEMPTS_TEST)
	set(GLOBAL_COMPILE_DEFINITIONS "${GLOBAL_COMPILE_DEFINITIONS};JVX_DEFAULT_NUMBER_OF_POSTPONE_ATTEMPTS_TEST=${JVX_DEFAULT_NUMBER_OF_POSTPONE_ATTEMPTS_TEST}")
endif()

if(JVX_GLOBAL_BUFFERING_VERBOSE)
	set(GLOBAL_COMPILE_DEFINITIONS "${GLOBAL_COMPILE_DEFINITIONS};JVX_GLOBAL_BUFFERING_VERBOSE")
endif()

if(JVX_PERMIT_QCP_OPENGL)
	set(GLOBAL_COMPILE_DEFINITIONS "${GLOBAL_COMPILE_DEFINITIONS};JVX_PERMIT_QCP_OPENGL")
endif()

if(JVX_HOST_WITH_NO_ARGS)
	set(GLOBAL_COMPILE_DEFINITIONS "${GLOBAL_COMPILE_DEFINITIONS};JVX_HOST_WITH_NO_ARGS")
endif()

if(JVX_COMMAND_LINE_TOKENS_BUILDIN)
	set(GLOBAL_COMPILE_DEFINITIONS "${GLOBAL_COMPILE_DEFINITIONS};JVX_COMMAND_LINE_TOKENS_BUILDIN=\"${JVX_COMMAND_LINE_TOKENS_BUILDIN}\"")
endif()

## Add global defines
if(JVX_LIBHOST_WITH_JSON_SHOW)
	set(GLOBAL_COMPILE_DEFINITIONS "${GLOBAL_COMPILE_DEFINITIONS};JVX_LIBHOST_WITH_JSON_SHOW")
endif()