	message("<< Checking for added submodules in folder <${JVXRT_SUBMODULE_PATH}> >>")
	
  	set(JVX_CONFIGURED_SUBMODULES "")

	SUBDIRLIST(SUBDIRS ${JVXRT_SUBMODULE_PATH})
	message ("--> Sub directories to be evaluated: ${SUBDIRS}")
	# LABEL ADD SUB_PROJECTS HERE!
	FOREACH(subdir ${SUBDIRS})
		if(mysubmodules)
			message("Look for ${subdir} in list of allowed submodules: \"${mysubmodules}\"")
			list(FIND mysubmodules ${subdir} ifoundit)
			if(${ifoundit} GREATER -1)
				if(EXISTS ${JVXRT_SUBMODULE_PATH}/${subdir}/.jvxprj.base OR EXISTS ${JVXRT_SUBMODULE_PATH}/${subdir}/.jvxprj.audio OR EXISTS ${JVXRT_SUBMODULE_PATH}/${subdir}/.jvxprj)
					set(JVX_CONFIGURED_SUBMODULES "${JVX_CONFIGURED_SUBMODULES};${subdir}")
				else()
					message("|--> .jvxprj.base|.jvxprj.audio|.jvxprj not found in ${JVXRT_SUBMODULE_PATH}/${subdir}, NOT Building folder.")
				endif()
			else()
				message("|--> Project ${JVXRT_SUBMODULE_PATH}/${subdir} is not in list for allowed submodules.")
			endif()
		else()
			if(EXISTS ${JVXRT_SUBMODULE_PATH}/${subdir}/.jvxprj.base OR EXISTS ${JVXRT_SUBMODULE_PATH}/${subdir}/.jvxprj.audio OR EXISTS ${JVXRT_SUBMODULE_PATH}/${subdir}/.jvxprj)
				set(JVX_CONFIGURED_SUBMODULES "${JVX_CONFIGURED_SUBMODULES};${subdir}")
			else()
				message("|--> .jvxprj.base|.jvxprj.audio|.jvxprj not found in ${JVXRT_SUBMODULE_PATH}/${subdir}, NOT Building folder.")
			endif()
		endif()
	ENDFOREACH()
	
	set(JVX_CONFIGURED_AUDIO_SUBMODULES ${JVX_CONFIGURED_SUBMODULES})
	
	## message(FATAL_ERROR "Valid submodules : ${JVX_CONFIGURED_AUDIO_SUBMODULES}")	
	FOREACH(subdir ${JVX_CONFIGURED_SUBMODULES})
		message("XX> Building sub project in folder ${JVXRT_SUBMODULE_PATH}/${subdir}")
		set(JVX_FOLDER_HIERARCHIE_BASE_OLD ${JVX_FOLDER_HIERARCHIE_BASE})
		set(JVX_FOLDER_HIERARCHIE_BASE "${JVX_FOLDER_HIERARCHIE_BASE}/sub-projects/${subdir}")		
		add_subdirectory(${JVXRT_SUBMODULE_PATH}/${subdir} ${JVXRT_SUBPROJECTS_PATH_MAP}/${subdir})
		set(JVX_FOLDER_HIERARCHIE_BASE ${JVX_FOLDER_HIERARCHIE_BASE_OLD})
	ENDFOREACH()