set(SUBPRODUCT_AYFSTARTER_LIBS_INCLUDE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/sources/Libraries")
set(SUBPRODUCT_AYFSTARTER_LIBS_LIB_PATH "${CMAKE_CURRENT_SOURCE_DIR}/sources/Libraries")
set(SUBPRODUCT_AYFSTARTER_LIBS_BINARY_DIR "${CMAKE_CURRENT_BINARY_DIR}")
