#ifndef __IJVXDATACHAININTERCEPTORREPORT_H__
#define __IJVXDATACHAININTERCEPTORREPORT_H__

typedef enum
{
	JVX_INTERCEPTOR_REPORT_PROCESS_START_ENTER,
	JVX_INTERCEPTOR_REPORT_PROCESS_START_LEAVE,
	JVX_INTERCEPTOR_REPORT_PROCESS_BUFFER_ENTER,
	JVX_INTERCEPTOR_REPORT_PROCESS_BUFFER_LEAVE,
	JVX_INTERCEPTOR_REPORT_PROCESS_STOP_ENTER,
	JVX_INTERCEPTOR_REPORT_PROCESS_STOP_LEAVE
} jvxDataChainReportType;

JVX_INTERFACE IjvxDataChainInterceptorReport
{
public:
	virtual JVX_CALLINGCONVENTION ~IjvxDataChainInterceptorReport() {};
	
	virtual jvxErrorType JVX_CALLINGCONVENTION report_event_interceptor(jvxDataChainReportType tp, jvxSize interceptorid) = 0;
};

#endif
