#ifndef __ONEMEASUREMENTCHANNEL__H__
#define __ONEMEASUREMENTCHANNEL__H__

#include "jvx.h"

#define JVX_FLAG_IR_VALID 0x1
#define JVX_FLAG_MEAS_VALID 0x2
#define JVX_FLAG_TEST_VALID 0x4

/*
 * NOTE: This header file is being generated by cmake from file <jvxSpNMeasureIr_oneMeasurementChannel.h> to file <jvxSpNMeasureIr_props.h>
 * in the cause of the code generation for the produced component. It declares some component specific variable types that
 * must be known outside of the component.
 * The macro to output the header is
 * -> set(JVX_PROPERTY_ACCESS_HEADER_COMPONENT ${CMAKE_CURRENT_SOURCE_DIR}/include/jvxSpNMeasureIr_oneMeasurementChannel.h)
 * It is copied to the same directory as the component specific headers for component allocation and deallocation.
 */

class oneChannelRequestArgs
{
public:
	jvxBool recomputeIr;
	jvxData override_reg_min;
	jvxData override_reg_max;
	jvxData exponent;

	oneChannelRequestArgs()
	{
		recomputeIr = false;
		override_reg_min = 1e-16;
		override_reg_max = 1e-6;
		exponent = 4;
	};
};

class oneMeasurementChannel
{
public:
	jvxApiString nmChan;
	jvxApiString nmMeas;
	jvxApiString fileLocate;
	jvxData* bufIr;
	jvxData* bufMeas;
	jvxData* bufTest;
	jvxSize lBuf;
	jvxCBitField validFlds;
	jvxSize rate;

	jvxData freq_low_start_hz;
	jvxData freq_low_stop_hz;
	jvxData freq_up_start_hz;
	jvxData freq_up_stop_hz;

	oneChannelRequestArgs* args = nullptr;

	oneMeasurementChannel()
	{
		bufIr = NULL;
		bufMeas = NULL;
		bufTest = NULL;
		lBuf = 0;
		validFlds = 0;
		rate = 0;

		freq_low_start_hz = 0;
		freq_low_stop_hz = 0;
		freq_up_start_hz = 0;
		freq_up_stop_hz = 0;

		
	};
};

#endif