#define JVX_GLUE_TOKEN(TOKEN1, TOKEN2) (TOKEN1 ## TOKEN2)

#if defined(JVX_SYS_WINDOWS_MSVC_64BIT) || defined(JVX_SYS_WINDOWS_MSVC_32BIT)
extern FUNC_CORE_PROT_RETURNVAL FUNC_CORE_PROT_DECLARE(FUNC_CORE_PROT_ARGS);
	FUNC_CORE_PROT_RETURNVAL FUNC_CORE_PROT_DECLARE_LOCAL(FUNC_CORE_PROT_ARGS)
#else
	FUNC_CORE_PROT_RETURNVAL __attribute__((weak)) FUNC_CORE_PROT_DECLARE(FUNC_CORE_PROT_ARGS)

#endif
