#

message(" -- CMake Linux for Raspi toolchain -- ")
# Standard settings
set (CMAKE_SYSTEM_NAME Linux)
set (CMAKE_SYSTEM_VERSION 1)
set (UNIX True)
set (JVX_CROSS_COMPILE True)

# specify the cross compiler
# JVX_LINUX_CROSSCOMPILER_ROOT -> /path/to/x-tools/toolchain
# JVX_LINUX_CROSSCOMPILER_LIB_ROOT -> /path/to/entry/raspberry/fs
# JVX_CROSSCOMPILE_PREFIX -> arm-linux-gnueabihf

set(JVX_XTOOLCHAIN_ROOT /home/hauke/CROSS_BUILD)
set(JVX_XTOOLCHAIN_DIRECTORY /home/hauke/CROSS_BUILD/bin)
set(JVX_XTOOLCHAIN_TRIPLE arm-linux-gnueabihf)
set(JVX_XTOOLCHAIN_MOUNTROOT /home/hauke/RPI_ROOT)

#SET(CMAKE_SYSROOT ${JVX_XTOOLCHAIN_ROOT})
SET(CMAKE_SYSROOT ${JVX_XTOOLCHAIN_MOUNTROOT})

link_directories(SYSTEM "${CMAKE_SYSROOT}/usr/lib/gcc/${JVX_XTOOLCHAIN_TRIPLE}/4.9.2")
# Set paths to compilers
SET(CMAKE_C_COMPILER ${JVX_XTOOLCHAIN_DIRECTORY}/${JVX_XTOOLCHAIN_TRIPLE}-gcc)
SET(CMAKE_CXX_COMPILER ${JVX_XTOOLCHAIN_DIRECTORY}/${JVX_XTOOLCHAIN_TRIPLE}-g++)

SET(CMAKE_FIND_ROOT_PATH ${JVX_XTOOLCHAIN_MOUNTROOT})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
