#ifndef __UMAINWINDOW_DEFINES_H__
#define __UMAINWINDOW_DEFINES_H__

#define JVX_QT_POSITION_SEQUENCE_DOCK_WIDGET Qt::RightDockWidgetArea
#define JVX_QT_POSITION_REALTIMEVIEWER_DOCK_WIDGET Qt::RightDockWidgetArea
#define JVX_QT_POSITION_MESSAGE_DOCK_WIDGET Qt::BottomDockWidgetArea
#define JVX_QT_COLOR_WARNING Qt::blue
#define JVX_QT_COLOR_ERROR Qt::red
#define JVX_QT_COLOR_SUCCESS Qt::green
#define JVX_QT_COLOR_INFORM Qt::black
#define JVX_QT_WIDTH_BITFIELD_ONE_UNIT 5

#define JVX_MARGIN_RT_VIEWER_TOP 2
#define JVX_MARGIN_RT_VIEWER_LEFT 2
#define JVX_MARGIN_RT_VIEWER_RIGHT 2
#define JVX_MARGIN_RT_VIEWER_BOTTOM 2
#define JVX_MARGIN_RT_VIEWER_SPACING 5

#define JVX_NUM_DIGITS_PARAMS 3

#define JVX_EPSILON 0.001

#define JVX_PIXEL_SIZE_FONTS_PLOT_AXIS 9

#endif