#ifndef __CJVXHOSTJVX_CONFIG_H__
#define __CJVXHOSTJVX_CONFIG_H__

#define SECTIONNAME_ALL_SUBSECTIONS "host_allSubSections"

#define SECTIONNAME_ALL_EXTERNAL_ENTRIES "host_allExternalEntries"
#define SECTIONNAME_ALL_EXTERNAL_MODULE_ENTRIES "host_allExternalModEntries"

#define SECTIONNAME_NUMSLOTS_TECHNOLOGY_PREFIX "host_slotnum_technology_"
#define SECTIONNAME_STATE_TECHNOLOGY_PREFIX "host_state_technology_"
#define SECTIONNAME_NUMSLOTS_DEVICE_PREFIX "host_slotnum_device_"
#define SECTIONNAME_STATE_DEVICE_PREFIX "host_state_device_"
#define SECTIONNAME_SUBSECTION_TECHNOLOGY_PREFIX "host_subsection_technology_"
#define SECTIONNAME_SUBSECTION_DEVICE_PREFIX "host_subsection_device_"
#define SECTIONNAME_NAME_TECHNOLOGY_PREFIX "host_name_technology_"
#define SECTIONNAME_NAME_DEVICE_PREFIX "host_name_device_"

#define SECTIONNAME_NUMSLOTS_ENDPOINT_PREFIX "host_slotnum_endpoint_"
#define SECTIONNAME_STATE_ENDPOINT_PREFIX "host_state_endpoint_"
#define SECTIONNAME_SUBSECTION_ENDPOINT_PREFIX "host_subsection_endpoint_"
#define SECTIONNAME_NAME_ENDPOINT_PREFIX "host_name_endpoint_"

#define SECTIONNAME_NUMSLOTS_SIMPLETYPE_PREFIX "host_slotnum_simpletype_"
#define SECTIONNAME_STATE_SIMPLETYPE_PREFIX "host_state_simpletype_"
#define SECTIONNAME_SUBSECTION_SIMPLETYPE_PREFIX "host_subsection_simpletype_"
#define SECTIONNAME_NAME_SIMPLETYPE_PREFIX "host_name_simpletype_"


// SCANNER TECHNOLOGIES

#define SECTIONNAME_NAME_SCANNER_TECHNOLOGY "host_name_scannertechnology"
#define SECTIONNAME_STATE_SCANNER_TECHNOLOGY "host_state_scannertechnology"

#define SECTIONNAME_SUBSECTION_SCANNER_TECHNOLOGY "host_subsection_scannertechnology"

// SCANNER DEVICES

#define SECTIONNAME_NAME_SCANNER_DEVICE "host_name_scannerdevice"
#define SECTIONNAME_STATE_SCANNER_DEVICE "host_state_scannerdevice"

#define SECTIONNAME_SUBSECTION_SCANNER_DEVICE "host_subsection_scannerdevice"

// SPECPROC TECHNOLOGIES

#define SECTIONNAME_NAME_SPECPROC_TECHNOLOGY "host_name_spectrumprocessortechnology"
#define SECTIONNAME_STATE_SPECPROC_TECHNOLOGY "host_state_spectrumprocessortechnology"

#define SECTIONNAME_SUBSECTION_SPECPROC_TECHNOLOGY "host_subsection_spectrumprocessortechnology"

// SPECPROC DEVICES

#define SECTIONNAME_NAME_SPECPROC_DEVICE "host_name_spectrumprocessordevice"
#define SECTIONNAME_STATE_SPECPROC_DEVICE "host_state_spectrumprocessordevice"

#define SECTIONNAME_SUBSECTION_SPECPROC_DEVICE "host_subsection_spectrumprocessordevice"

// LAMP TECHNOLOGIES

#define SECTIONNAME_NAME_LAMP_TECHNOLOGY "host_name_lamptechnology"
#define SECTIONNAME_STATE_LAMP_TECHNOLOGY "host_state_lamptechnology"

#define SECTIONNAME_SUBSECTION_LAMP_TECHNOLOGY "host_subsection_lamptechnology"

// LAMP DEVICES

#define SECTIONNAME_NAME_LAMP_DEVICE "host_name_lampdevice"
#define SECTIONNAME_STATE_LAMP_DEVICE "host_state_lampdevice"

#define SECTIONNAME_SUBSECTION_LAMP_DEVICE "host_subsection_lampdevice"

// CAMERA TECHNOLOGIES

#define SECTIONNAME_NAME_CAMERA_TECHNOLOGY "host_name_cameratechnology"
#define SECTIONNAME_STATE_CAMERA_TECHNOLOGY "host_state_cameratechnology"

#define SECTIONNAME_SUBSECTION_CAMERA_TECHNOLOGY "host_subsection_cameratechnology"

// CAMERA DEVICES

#define SECTIONNAME_NAME_CAMERA_DEVICE "host_name_cameradevice"
#define SECTIONNAME_STATE_CAMERA_DEVICE "host_state_cameradevice"

#define SECTIONNAME_SUBSECTION_CAMERA_DEVICE "host_subsection_cameradevice"
// ASCAN ENDPOINTS

#define SECTIONNAME_NAME_ASCANENDPOINT "host_name_ascanendpoint"
#define SECTIONNAME_STATE_ASCANENDPOINT "host_state_ascanendpoint"

#define SECTIONNAME_SUBSECTION_ASCANENDPOINT "host_subsection_ascanendpoint"

#endif