enum class jvxLogLevel
{
	JVX_LOGLEVEL_0_NORMAL_OPERATION_WITH_LOW_DEGREE_OUTPUT = 0,
	JVX_LOGLEVEL_1_NORMAL_OPERATION_WITH_AVRG_DEGREE_OUTPUT = 1,
	JVX_LOGLEVEL_2_NORMAL_OPERATION_WITH_HIGH_DEGREE_OUTPUT = 2,
	JVX_LOGLEVEL_3_DEBUG_OPERATION_WITH_LOW_DEGREE_OUTPUT = 3,
	JVX_LOGLEVEL_4_DEBUG_OPERATION_WITH_AVRG_DEGREE_DEBUG = 4,
	JVX_LOGLEVEL_5_DEBUG_OPERATION_WITH_HIGH_DEGREE_DEBUG = 5,
	JVX_LOGLEVEL_6_OPERATION = 6,
	JVX_LOGLEVEL_7_OPERATION = 7,
	JVX_LOGLEVEL_8_OPERATION = 8,
	JVX_LOGLEVEL_9_OPERATION = 9,
	JVX_LOGLEVEL_10_OPERATION = 10
};
