#ifndef __TJVX_TEXT2SPEECH_H__
#define __TJVX_TEXT2SPEECH_H__

typedef enum
{
    JVX_TEXT2SPEECH_8KHZ16BITMONO,
	JVX_TEXT2SPEECH_16KHZ16BITMONO,
    JVX_TEXT2SPEECH_32KHZ16BITMONO,
	JVX_TEXT2SPEECH_44KHZ16BITMONO,
    JVX_TEXT2SPEECH_48KHZ16BITMONO,
	JVX_TEXT2SPEECH_LIMIT
} jvxText2SpeechFormat;

#endif
