#ifndef __UMAINWINDOW_CONFIG_H__
#define __UMAINWINDOW_CONFIG_H__

// =====================================================================
// Local configuration lookup token for this host
// =====================================================================
#define JVX_QT_HOST_1_SECTION_MAIN "jvxQtHost1_main"
#define JVX_QT_HOST_1_SECTION_COMPONENTS "jvxQtHost1_components"
#define JVX_QT_HOST_1_EXTERNAL_TRIGGER  "jvxQtHost1_exttrigger"
#define JVX_QT_HOST_1_ENTRY_UPDATERATE_RT_PLOTS "jvxQtHost1_updaterate_plots_ms"
#define JVX_QT_HOST_1_ENTRY_UPDATERATE_RT_PROPS "jvxQtHost1_updaterate_props_ms"
#define JVX_QT_HOST_1_ENTRY_UPDATERATE_CENTRAL "jvxQtHost1_updaterate_central_ms"

// Print all configuration text in compact form
#define JVX_QT_HOST_1_PRINT_COMPACT_FORM false

#define JVX_COMMON_PROPERTIES_HOST_AUTOSTART "JVX_COMMON_PROPERTIES_HOST_AUTOSTART"
#define JVX_COMMON_PROPERTIES_HOST_AUTOSTOP "JVX_COMMON_PROPERTIES_HOST_AUTOSTOP"

#define JVX_COMMON_PROPERTIES_HOST_PERIOD_SEQ "JVX_COMMON_PROPERTIES_HOST_PERIOD_SEQ"
#define JVX_COMMON_PROPERTIES_HOST_PERIOD_MAINCENTRAL "JVX_COMMON_PROPERTIES_HOST_PERIOD_MAINCENTRAL"
#define JVX_COMMON_PROPERTIES_HOST_PERIOD_RTVIEWER_PROPS "JVX_COMMON_PROPERTIES_HOST_PERIOD_RTVIEWER_PROPS"
#define JVX_COMMON_PROPERTIES_HOST_PERIOD_RTVIEWER_PLOTS "JVX_COMMON_PROPERTIES_HOST_PERIOD_RTVIEWER_PLOTS"

#define JVX_COMMON_PROPERTIES_HOST_VIEW_PROPS_VISIBLE "JVX_COMMON_PROPERTIES_HOST_VIEW_PROPS_VISIBLE"
#define JVX_COMMON_PROPERTIES_HOST_VIEW_PLOTS_VISIBLE "JVX_COMMON_PROPERTIES_HOST_VIEW_PLOTS_VISIBLE"
#define JVX_COMMON_PROPERTIES_HOST_VIEW_SEQ_VISIBLE "JVX_COMMON_PROPERTIES_HOST_VIEW_SEQ_VISIBLE"
#define JVX_COMMON_PROPERTIES_HOST_VIEW_CONNECTIONS_VISIBLE "JVX_COMMON_PROPERTIES_HOST_VIEW_CONNECTIONS_VISIBLE"

#define JVX_COMMON_PROPERTIES_HOST_VIEW_TAB_BITFIELD "JVX_COMMON_PROPERTIES_HOST_VIEW_TAB_BITFIELD" 

#define JVX_COMMON_PROPERTIES_HOST_SECTION_NAME "host_allExternalEntries"

#endif