import 'package:flutter/foundation.dart';

enum JvxComponentTypeEnum {
  // NOT AUDIO SPECIFIC
  JVX_COMPONENT_UNKNOWN,
  JVX_COMPONENT_SIGNAL_PROCESSING_TECHNOLOGY,
  JVX_COMPONENT_SIGNAL_PROCESSING_DEVICE,
  JVX_COMPONENT_SIGNAL_PROCESSING_NODE,
  JVX_COMPONENT_AUDIO_TECHNOLOGY,
  JVX_COMPONENT_AUDIO_DEVICE,
  JVX_COMPONENT_AUDIO_NODE,
  JVX_COMPONENT_VIDEO_TECHNOLOGY,
  JVX_COMPONENT_VIDEO_DEVICE,
  JVX_COMPONENT_VIDEO_NODE,
  JVX_COMPONENT_APPLICATION_CONTROLLER_TECHNOLOGY,
  JVX_COMPONENT_APPLICATION_CONTROLLER_DEVICE,
  JVX_COMPONENT_APPLICATION_CONTROLLER_NODE,
  JVX_COMPONENT_CUSTOM_TECHNOLOGY,
  JVX_COMPONENT_CUSTOM_DEVICE,
  JVX_COMPONENT_CUSTOM_NODE,
  JVX_COMPONENT_EXTERNAL_TECHNOLOGY,
  JVX_COMPONENT_EXTERNAL_DEVICE,
  JVX_COMPONENT_EXTERNAL_NODE,
  JVX_COMPONENT_DYNAMIC_NODE,
  JVX_COMPONENT_PACKAGE,
  JVX_COMPONENT_MIN_HOST,
  JVX_COMPONENT_FACTORY_HOST,
  JVX_COMPONENT_HOST,
  JVX_COMPONENT_EVENTLOOP,
  JVX_COMPONENT_DATALOGGER,
  JVX_COMPONENT_DATALOGREADER,
  JVX_COMPONENT_CONNECTION,
  JVX_COMPONENT_CONFIG_PROCESSOR,
  JVX_COMPONENT_EXTERNAL_CALL,
  JVX_COMPONENT_THREADCONTROLLER,
  JVX_COMPONENT_THREADS,
  JVX_COMPONENT_SHARED_MEMORY,
  JVX_COMPONENT_TEXT2SPEECH,
  JVX_COMPONENT_SYSTEM_TEXT_LOG,
  JVX_COMPONENT_LOCAL_TEXT_LOG,
  JVX_COMPONENT_CRYPT,
  JVX_COMPONENT_WEBSERVER,
  JVX_COMPONENT_REMOTE_CALL,
  JVX_COMPONENT_PACKETFILTER_RULE,
  JVX_COMPONENT_LOGREMOTEHANDLER,

  // AUDIO SPECIFIC
  JVX_COMPONENT_AUDIO_CODEC,
  JVX_COMPONENT_AUDIO_ENCODER,
  JVX_COMPONENT_AUDIO_DECODER,
  JVX_COMPONENT_RT_AUDIO_FILE_READER,
  JVX_COMPONENT_RT_AUDIO_FILE_WRITER,
  JVX_COMPONENT_RESAMPLER,
  JVX_COMPONENT_DATACONVERTER,

  // NOT AUDIO SPECIFIC
  JVX_COMPONENT_PROCESSING_GROUP,
  JVX_COMPONENT_PROCESSING_PROCESS,
  JVX_COMPONENT_OFF_HOST,
  JVX_COMPONENT_INTERCEPTOR,
  JVX_COMPONENT_SYSTEM_AUTOMATION
}

// Enum handling does not work with generic functions/methods
// https://stackoverflow.com/questions/59362403/dart-constrain-a-generic-type-t-to-an-enum

extension JvxComponentTypeEEnum on JvxComponentTypeEnum {
  String get txt => describeEnum(this);
  static JvxComponentTypeEnum fromInt(int val) {
    JvxComponentTypeEnum ss = JvxComponentTypeEnum.values[0];
    if (val < JvxComponentTypeEnum.values.length) {
      ss = JvxComponentTypeEnum.values[val];
    }
    return ss;
  }
}
