function CH = cheader_begin(filename, scriptname)
[CH.fid msg] = fopen(filename, 'wt');
[dummy, name, ext]=fileparts(filename);
CH.token = [ '__' upper(name) '__H__'];
if(strcmp(msg, '') == 0)
    disp(msg)
end
fprintf(CH.fid, [
    '// GENERATED FILE (%s)\n// written by "%s"\n' ...
    '// (C) Binaurics Audio GmbH\n\n' ...
    '#ifndef %s\n' ...
    '#define %s\n\n'], ...
        datestr(now, 0), ...
        scriptname,...
        CH.token, CH.token...
);
