#ifndef _TJVXWEBSERVERHOST_H__
#define _TJVXWEBSERVERHOST_H__

typedef enum
{
	JVX_WEB_SERVER_REPLACE_NONE,
	JVX_WEB_SERVER_REPLACE_COMPONENT_TYPE
} jvxOneHttpReplaceType;
typedef struct
{
	std::string expression;
	jvxCBitField purp;
	jvxOneHttpReplaceType repl;
} jvxOneHttpRequestDefinition;

#define JVX_NUMBER_WEBSERVER_CO_HOST_DEFINITIONS  5
#define JVX_HTTP_REPLACE_TOKEN "JVX_HTTP_REPLACE"

static jvxOneHttpRequestDefinition theJvxWebServerCoHostDefinitions[JVX_NUMBER_WEBSERVER_CO_HOST_DEFINITIONS] = 
{
	// First 4 entries only to address console backend
	{"/jvx/host/commands/", JVX_WEB_SERVER_URI_POST_HANDLER_PURP, JVX_WEB_SERVER_REPLACE_NONE },
	{"/jvx/host/components/" JVX_HTTP_REPLACE_TOKEN, JVX_WEB_SERVER_URI_GET_HANDLER_PURP | JVX_WEB_SERVER_URI_PUT_HANDLER_PURP | JVX_WEB_SERVER_URI_POST_HANDLER_PURP, 
		JVX_WEB_SERVER_REPLACE_COMPONENT_TYPE },
	{"/jvx/host/sequencer/", JVX_WEB_SERVER_URI_GET_HANDLER_PURP | JVX_WEB_SERVER_URI_POST_HANDLER_PURP, JVX_WEB_SERVER_REPLACE_NONE },
	{"/jvx/host/connections/", JVX_WEB_SERVER_URI_GET_HANDLER_PURP | JVX_WEB_SERVER_URI_POST_HANDLER_PURP, JVX_WEB_SERVER_REPLACE_NONE },

	// This entry to address web specific functionality
	{"/jvx/host/web/", JVX_WEB_SERVER_URI_GET_HANDLER_PURP | JVX_WEB_SERVER_URI_POST_HANDLER_PURP }
};

//typedef jvxSize theJvxWebServerCoHostIds[JVX_NUMBER_WEBSERVER_CO_HOST_DEFINITIONS];

#define JVX_NUMBER_WEBSERVER_WS_HOST_DEFINITIONS  1

static jvxOneHttpRequestDefinition theJvxWebServerWsHostDefinitions[JVX_NUMBER_WEBSERVER_WS_HOST_DEFINITIONS] =
{	
	{ "/jvx/host/socket/", (JVX_WEB_SERVER_URI_WEBSOCKET_CONNECT_HANDLER_PURP |
	JVX_WEB_SERVER_URI_WEBSOCKET_READY_HANDLER_PURP |
		JVX_WEB_SERVER_URI_WEBSOCKET_DATA_HANDLER_PURP |
		JVX_WEB_SERVER_URI_WEBSOCKET_CLOSE_HANDLER_PURP), JVX_WEB_SERVER_REPLACE_NONE }
};

//typedef jvxSize theJvxWebServerWsHostIds[JVX_NUMBER_WEBSERVER_WS_HOST_DEFINITIONS];

#endif

