#ifndef __TJVXGENERIWRAPPERAPI_H__
#define __TJVXGENERIWRAPPERAPI_H__

typedef enum
{
	JVX_GENERIC_WRAPPER_CHANNEL_TYPE_NONE = 0,
	JVX_GENERIC_WRAPPER_CHANNEL_TYPE_DEVICE = 1,
	JVX_GENERIC_WRAPPER_CHANNEL_TYPE_FILE = 2,
	JVX_GENERIC_WRAPPER_CHANNEL_TYPE_EXTERNAL = 3,
	JVX_GENERIC_WRAPPER_CHANNEL_TYPE_DUMMY = 4,
	JVX_GENERIC_WRAPPER_CHANNEL_TYPE_LIMIT 
} jvxGenericWrapperChannelType;

#endif