#ifndef _JVX_SYSTEM_THREADS_H__
#define _JVX_SYSTEM_THREADS_H__

#define JVX_THREAD_HANDLE HANDLE
#define JVX_NULLTHREAD NULL
#define JVX_THREAD_ID DWORD
#define JVX_THREAD_EXIT_CODE DWORD
#define JVX_THREAD_EXIT_NORMAL 0
#define JVX_THREAD_EXIT_ERROR 1
#define JVX_STILL_ACTIVE STILL_ACTIVE
#define JVX_RETURN_THREAD(a) return(a)
#define JVX_GET_CURRENT_THREAD_ID GetCurrentThreadId
#define JVX_GET_CURRENT_THREAD_HANDLE GetCurrentThread
#define JVX_THREAD_RETURN_TYPE DWORD
#define JVX_COMPARE_THREADS(a,b) (a == b)
#define JVX_THREAD_ENTRY_FUNCTION(fName,param) static JVX_THREAD_RETURN_TYPE WINAPI fName(LPVOID param)
#define JVX_CREATE_THREAD(hdl, entry, param, id) hdl = CreateThread(NULL, 0, entry, param, 0, &id);
#define JVX_WAIT_TIMEOUT DWORD
#define JVX_NOTIFY_HANDLE HANDLE
#define JVX_INITIALIZE_NOTIFICATION(a) a = CreateEvent(NULL, false, false, NULL)
#define JVX_TERMINATE_NOTIFICATION(a) CloseHandle(a)
#define JVX_WAIT_FOR_NOTIFICATION_I(hdl)
#define JVX_WAIT_FOR_NOTIFICATION_II_MS(a, b)  WaitForSingleObject(a, (JVX_WAIT_TIMEOUT)b)
#define JVX_WAIT_FOR_NOTIFICATION_II_S(a, b)  WaitForSingleObject(a, (JVX_WAIT_TIMEOUT)(b*1000))
#define JVX_WAIT_FOR_NOTIFICATION_II_INF(a)  WaitForSingleObject(a, INFINITE)
#define JVX_WAIT_FOR_CHECK_RETRIGGER_NOTIFICATION_I(a) false
#define JVX_CHECK_RETRIGGER_NOTIFICATION(a) false
#define JVX_WAIT_FOR_NOTIFICATION_II_CLEAR(a)
#define JVX_WAIT_SUCCESS WAIT_OBJECT_0
#define JVX_WAIT_RESULT DWORD
#define JVX_TERMINATE_THREAD(thrdHandle, exitCode) TerminateThread(thrdHandle, exitCode);
#define JVX_SET_NOTIFICATION(a) SetEvent(a)
#define JVX_RESET_NOTIFICATION(a) ResetEvent(a)
#define JVX_THREAD_PRIORITY DWORD
#define JVX_SET_THREAD_PRIORITY(hdl,prioVal) SetThreadPriority(hdl,prioVal)
#define JVX_GET_THREAD_PRIORITY(a) GetThreadPriority(a)
#define JVX_THREAD_PRIORITY_REALTIME THREAD_PRIORITY_TIME_CRITICAL
#define JVX_THREAD_BACKGROUND_BEGIN(tHdl) SetThreadPriority(tHdl, THREAD_MODE_BACKGROUND_BEGIN)
#define JVX_THREAD_BACKGROUND_END(tHdl) SetThreadPriority(tHdl, THREAD_MODE_BACKGROUND_END)
#define JVX_THREAD_PRIORITY_NORMAL THREAD_PRIORITY_NORMAL
#define JVX_WAIT_FOR_THREAD_TERMINATE_MS(a,b) WaitForSingleObject(a, (JVX_WAIT_TIMEOUT)b)
#define JVX_WAIT_FOR_THREAD_TERMINATE_INF(a)  WaitForSingleObject(a, INFINITE)
#define JVX_INFINITE_MS JVX_SIZE_UNSELECTED
#define JVX_SLEEP_MS(a) Sleep((DWORD)a)
#define JVX_SLEEP_S(a) Sleep(a*1000)

#define JVX_NOTIFY_HANDLE_2WAIT_DECLARE(notifyHdl) JVX_NOTIFY_HANDLE notifyHdl
#define JVX_INITIALIZE_NOTIFICATION_2WAIT(a) JVX_INITIALIZE_NOTIFICATION(a)
#define JVX_TERMINATE_NOTIFICATION_2WAIT(a) JVX_TERMINATE_NOTIFICATION(a)
#define JVX_SET_NOTIFICATION_2WAIT(a) JVX_SET_NOTIFICATION(a)
#define JVX_EVENT_WAIT_2WAIT(a) 
#define JVX_INVALID_HANDLE_VALUE_2WAIT JVX_INVALID_HANDLE_VALUE

#define JVX_THREAD_ID_UINT32(tid) ((jvxUInt32) tid)
#endif