
#ifndef __CAYFAUTOMATIONMODULESTYPES_H__
#define __CAYFAUTOMATIONMODULESTYPES_H__

namespace CayfAutomationModules
{
	enum class ayfEstablishedProcessType
	{
		AYF_ESTABLISHED_PROCESS_UNKNOWN,
		AYF_ESTABLISHED_PROCESS_SRC2SNK,
		AYF_ESTABLISHED_PROCESS_SRC2SNKPRECHAIN,
		AYF_ESTABLISHED_PROCESS_SRC2SNKPRECHAINPRICHAIN,
		AYF_ESTABLISHED_PROCESS_SYNCIO
	};
};

#endif
