[package]
name = "ayfstarterlibdbgrs"
publish = false
edition = "2021"

[lib]
crate-type = ["staticlib"]

[features]                                                                                                  
default = []
jvx-system-use-data-format-float = ["jvx_dsp_base/jvx-system-use-data-format-float"]
jvx-allow-profiler-data-macros = []

[dependencies]
jvx_dsp_base = { path = "../../../../../../jvxLibraries/jvx-dsp-base-rust" }
ayfstarterlibrs = { path = "../ayfstarterlib" }
