[package]
name = "ayfstarterlibrs"
publish = false
edition = "2021"

[lib]
crate-type = ["lib", "staticlib"]

[features]                                                                                                  
default = []
jvx-system-use-data-format-float = ["jvx_dsp_base/jvx-system-use-data-format-float"]

[dependencies]
jvx_dsp_base = { path = "../../../../../../jvxLibraries/jvx-dsp-base-rust" }
